version: '2'
services:
    databuild_java-app:
        image: databuild_java
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://databuild_java-mysql:3306/databuild_java?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    databuild_java-mysql:
        extends:
            file: mysql.yml
            service: databuild_java-mysql
